final Map<String, String> iconsPath = {
  "sunny": "assets/weatherCondition/sunny.png",
  "clear": "assets/weatherCondition/Night Clear moon.png",
  "partly cloudy": "assets/weatherCondition/partly-cloudy.png",
  "cloudy": "assets/weatherCondition/cloudy.png",
  "patchy rain nearby":"assets/weatherCondition/rain.png",
  "overcast": "assets/weatherCondition/cloudy.png",
  "mist": "assets/weatherCondition/wind.png",
  "patchy rain possible": "assets/weatherCondition/rain.png",
  "patchy snow possible": "assets/weatherCondition/snowflake.png",
  "patchy sleet possible": "assets/weatherCondition/sleet.png",
  "patchy freezing drizzle possible": "assets/weatherCondition/sleet.png",
  "thundery outbreaks possible": "assets/weatherCondition/thunderStorm.png",
  "blowing snow": "assets/weatherCondition/snowflake.png",
  "blizzard": "assets/weatherCondition/snowflake.png",
  "fog": "assets/weatherCondition/wind.png",
  "freezing fog": "assets/weatherCondition/wind.png",
  "patchy light drizzle": "assets/weatherCondition/rain.png",
  "light drizzle": "assets/weatherCondition/rain.png",
  "freezing drizzle": "assets/weatherCondition/rain.png",
  "heavy freezing drizzle": "assets/weatherCondition/rain.png",
  "patchy light rain": "assets/weatherCondition/rain.png",
  "light rain": "assets/weatherCondition/rain.png",
  "moderate rain at times": "assets/weatherCondition/rain.png",
  "moderate rain": "assets/weatherCondition/rain.png",
  "heavy rain at times": "assets/weatherCondition/rain.png",
  "heavy rain": "assets/weatherCondition/rain.png",
  "light freezing rain": "assets/weatherCondition/sleet.png",
  "moderate or heavy freezing rain": "assets/weatherCondition/sleet.png",
  "light sleet": "assets/weatherCondition/sleet.png",
  "moderate or heavy sleet": "assets/weatherCondition/sleet.png",
  "patchy light snow": "assets/weatherCondition/snowflake.png",
  "light snow": "assets/weatherCondition/snowflake.png",
  "patchy moderate snow": "assets/weatherCondition/snowflake.png",
  "moderate snow": "assets/weatherCondition/snowflake.png",
  "patchy heavy snow": "assets/weatherCondition/snowflake.png",
  "heavy snow": "assets/weatherCondition/snowflake.png",
  "ice pellets": "assets/weatherCondition/snowflake.png",
  "light rain shower": "assets/weatherCondition/rain.png",
  "moderate or heavy rain shower": "assets/weatherCondition/rain.png",
  "torrential rain shower": "assets/weatherCondition/rain.png",
  "light sleet showers": "assets/weatherCondition/sleet.png",
  "moderate or heavy sleet showers": "assets/weatherCondition/sleet.png",
  "light snow showers": "assets/weatherCondition/snowflake.png",
  "moderate or heavy snow showers": "assets/weatherCondition/snowflake.png",
  "light showers of ice pellets": "assets/weatherCondition/snowflake.png",
  "moderate or heavy showers of ice pellets": "assets/weatherCondition/snowflake.png",
  "patchy light rain with thunder": "assets/weatherCondition/thunderStorm.png",
  "moderate or heavy rain with thunder": "assets/weatherCondition/thunderStorm.png",
  "patchy light snow with thunder": "assets/weatherCondition/thunderStorm.png",
  "moderate or heavy snow with thunder": "assets/weatherCondition/thunderStorm.png",
};


final Map<int, String> airQuality={
  1:'Good',
  2:'Moderate',
  3:'Moderately Unhealthy',
  4:'Unhealthy',
  5:'Very Unhealthy',
  6:'Hazardous'
};
